# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 18:31
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.IntegerField()),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_number', models.IntegerField()),
                ('purchase_value', models.IntegerField()),
                ('up_date', models.DateField()),
                ('down_date', models.DateField(blank=True)),
                ('annex', models.FileField(blank=True, upload_to=b'')),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Airport')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Family')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bp', models.PositiveIntegerField(unique=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Airport')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Area')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_cost', models.IntegerField()),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SparePartHistoricPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('price', models.IntegerField()),
                ('spare_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.SparePart')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Subfamily',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='workorder',
            name='work_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.WorkType'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='spare_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.SparePart'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='work_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.WorkOrder'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='subfamily',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Subfamily'),
        ),
        migrations.AddField(
            model_name='history',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Status'),
        ),
    ]
