# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 15:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='history',
            name='machine_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='annex',
            field=models.FileField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='inventory',
            name='down_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='machine_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='purchase_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='inventory',
            name='up_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
