# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 11:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('machine_number', models.PositiveIntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='airport',
            name='id',
        ),
        migrations.RemoveField(
            model_name='area',
            name='id',
        ),
        migrations.RemoveField(
            model_name='family',
            name='id',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='id',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='id',
        ),
        migrations.RemoveField(
            model_name='status',
            name='id',
        ),
        migrations.RemoveField(
            model_name='subfamily',
            name='id',
        ),
        migrations.RemoveField(
            model_name='worktype',
            name='id',
        ),
        migrations.AddField(
            model_name='workorder',
            name='mechanic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='area',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='machine_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Machine'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='machine_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Machine'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bp',
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='spareparthistoricprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subfamily',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='worktype',
            name='name',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='machine',
            name='airport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Airport'),
        ),
    ]
