# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0002_auto_20170202_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='down_date',
            field=models.DateField(null=True),
        ),
    ]
