# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('maintenance', '0003_area_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='airport',
        ),
        migrations.RemoveField(
            model_name='user',
            name='area',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
