# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_auto_20170202_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='down_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
