# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-02 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_auto_20170202_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='hour_base',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='hour_now',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='km_base',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='km_now',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='spareparthistoricprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
