# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('maintenance', '0005_auto_20170202_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hourmeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('hourmeter_to_date', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Odometer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('odometer_to_date', models.PositiveIntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='hour_base',
            new_name='hourmeter_base',
        ),
        migrations.RenameField(
            model_name='machine',
            old_name='km_base',
            new_name='odometer_base',
        ),
        migrations.RemoveField(
            model_name='history',
            name='date',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='family',
        ),
        migrations.RemoveField(
            model_name='inventory',
            name='subfamily',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='airport',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='hour_now',
        ),
        migrations.RemoveField(
            model_name='machine',
            name='km_now',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='date',
        ),
        migrations.AddField(
            model_name='airport',
            name='code',
            field=models.CharField(default=0, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='family',
            name='code',
            field=models.CharField(default=1, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='history',
            name='work_order',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='maintenance.WorkOrder'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='family',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.PROTECT, to='maintenance.Family'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='machine',
            name='subfamily',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.PROTECT, to='maintenance.Subfamily'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subfamily',
            name='code',
            field=models.CharField(default=7, max_length=10, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workorder',
            name='team_leader',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.PROTECT, related_name='team_leader', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='airport',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='family',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='spareparthistoricprice',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='subfamily',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='mechanic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mechanic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='odometer',
            name='machine_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Machine'),
        ),
        migrations.AddField(
            model_name='hourmeter',
            name='machine_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Machine'),
        ),
        migrations.AddField(
            model_name='machine',
            name='category',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='maintenance.Category'),
            preserve_default=False,
        ),
    ]
