# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 14:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0006_auto_20170203_1447'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('input_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='InstructionType',
            fields=[
                ('instruction_type', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MachineInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('input_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Input')),
                ('machine_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineInstruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('instruction_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Instruction')),
                ('machine_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Machine')),
            ],
        ),
        migrations.CreateModel(
            name='MachineSparePart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('machine_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Machine')),
            ],
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='spare_part',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='work_order',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='factory_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sparepart',
            name='sage_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subfamily',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='PurchaseOrder',
        ),
        migrations.AddField(
            model_name='machinesparepart',
            name='spare_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.SparePart'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='instruction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.InstructionType'),
        ),
        migrations.AddField(
            model_name='input',
            name='input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.InputType'),
        ),
    ]
