# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 14:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_auto_20170207_1435'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inputtype',
            old_name='input_type',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='instructiontype',
            old_name='instruction_type',
            new_name='name',
        ),
    ]
