# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0008_auto_20170207_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='input',
            name='id',
        ),
        migrations.AlterField(
            model_name='input',
            name='input_type',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='machineinput',
            unique_together=set([('machine_number', 'input_number', 'level')]),
        ),
        migrations.AlterUniqueTogether(
            name='machineinstruction',
            unique_together=set([('machine_number', 'instruction_number', 'level')]),
        ),
        migrations.DeleteModel(
            name='InputType',
        ),
    ]
