# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 15:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0009_auto_20170207_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='machine_number',
            field=models.ForeignKey(default=5555, on_delete=django.db.models.deletion.PROTECT, to='maintenance.Machine'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='machinesparepart',
            unique_together=set([('machine_number', 'spare_part', 'level')]),
        ),
    ]
