# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_auto_20170207_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='id',
        ),
        migrations.AddField(
            model_name='workorder',
            name='order_number',
            field=models.PositiveIntegerField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='factory_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='sage_number',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
