# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 14:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0011_auto_20170209_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mechanic', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='team_leader', to=settings.AUTH_USER_MODEL),
        ),
    ]
