# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0013_auto_20170209_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sparepart',
            name='name',
        ),
        migrations.AddField(
            model_name='sparepart',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sparepart',
            name='spare_part_type',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
