# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0014_auto_20170213_1257'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='level',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
