# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-17 12:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0015_workorder_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='team_leader',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='team_leader', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
