# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-20 13:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0017_machineinstruction_instruction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LubricationChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='LubricationChartDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('lubrication_chart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.LubricationChart')),
            ],
        ),
        migrations.CreateModel(
            name='MachineLubricationChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField()),
                ('lubrication_chart', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.LubricationChart')),
                ('machine_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.Machine')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='machinelubricationchart',
            unique_together=set([('machine_number', 'lubrication_chart', 'level')]),
        ),
    ]
