# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0018_auto_20170220_1327'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderWorkDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_work_description', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.WorkDescription')),
                ('order_number', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='maintenance.WorkOrder')),
            ],
        ),
        migrations.AlterField(
            model_name='lubricationchart',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
