# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-23 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0019_auto_20170223_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='annex',
            field=models.FileField(blank=True, upload_to=b''),
        ),
    ]
