# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-24 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0020_workorder_annex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='machine_number',
        ),
        migrations.RemoveField(
            model_name='history',
            name='status',
        ),
        migrations.RemoveField(
            model_name='history',
            name='work_order',
        ),
        migrations.RemoveField(
            model_name='hourmeter',
            name='machine_number',
        ),
        migrations.RemoveField(
            model_name='odometer',
            name='machine_number',
        ),
        migrations.AlterUniqueTogether(
            name='lubricationchartdescription',
            unique_together=set([('lubrication_chart', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='spareparthistoricprice',
            unique_together=set([('spare_part', 'date')]),
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='Hourmeter',
        ),
        migrations.DeleteModel(
            name='Odometer',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
    ]
