# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 16:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0022_purchaseorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='work_order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='maintenance.WorkOrder'),
        ),
    ]
