# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0023_auto_20170227_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='is_closed',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
